{ config, pkgs, inputs, ... }:

{
  home.username = "jd";
  home.homeDirectory = "/home/jd";
  # programs.git.enable = true;
  home.stateVersion = "25.05";
  programs.bash = {
    enable = true;
    shellAliases = {
      btw = "echo i use nixos, btw";
    };
  };
  imports = [
    ./modules/terminal.nix
  #   # inputs.niri.homeModules.niri
  #   inputs.dms.homeModules.dank-material-shell
  #   inputs.dms.homeModules.niri
  ];

  # programs.dank-material-shell = {
  #   enable = true;
  #   niri = {
  #     enableKeybinds = true;   # Sets static preset keybinds
  #     enableSpawn = true;      # Auto-start DMS with niri, if enabled

  #     includes = {
  #       enable = false;             # Enable config includes hack. Enabled by default.

  #       override = true;           # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
  #       originalFileName = "hm";   # A new name (without extension) for the config file generated by niri-flake.
  #       filesToInclude = [         # Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config
  #         "alttab"                 # Please note that niri will throw an error if any of these files are missing.
  #         "binds"
  #         "colors"
  #         "cursor"
  #         "layout"
  #         "outputs"
  #         "windowrules"
  #         "wpblur"
  #       ];
  #     };
  #   };

  #   systemd = {
  #     enable = true;             # Systemd service for auto-start
  #     restartIfChanged = true;   # Auto-restart dms.service when dank-material-shell changes
  #   };

  #   # Core features
  #   enableSystemMonitoring = true;     # System monitoring widgets (dgop)
  #   enableVPN = true;                  # VPN management widget
  #   enableDynamicTheming = true;       # Wallpaper-based theming (matugen)
  #   enableAudioWavelength = true;      # Audio visualizer (cava)
  #   enableCalendarEvents = true;       # Calendar integration (khal)

    
  # };

  # programs.niri = {
  #   enable = true;
  # };


  # xdg.dataFile."wayland-sessions/niri.desktop".text = ''
  #   [Desktop Entry]
  #   Name=Niri
  #   Comment=A scrollable-tiling Wayland compositor
  #   Exec=${config.programs.niri.package}/bin/niri --session
  #   Type=Application
  #   DesktopNames=niri
  # '';


  home.packages = with pkgs; [
    evince
    # vlc
    xournalpp
    rnote
    zoom-us
    # inputs.nixpkgs-unstable.brave
    # apacheOpenOffice
  ];

  dconf.settings = {
    "org/gnome/settings-daemon/plugins/media-keys" = {
      volume-step = 1;
    };
  };

  # Pastikan module git diaktifkan
  programs.git = {
    enable = true;
    settings = {
      user = {
        name = "jajatda";
        email = "jajatd4r@gmail.com";
      };

      commit.gpgSign = true;
      gpg.format = "ssh";
      user.signingKey = "/home/jd/.ssh/id_ed25519.pub";
      
      init.defaultBranch = "main";
      safe.directory = "*"; # Berguna agar git tidak error di direktori flake
      pull.rebase = true;

      # Alias opsional untuk efisiensi
      alias = {
        lg = "log --graph --oneline --decorate --all";
        s = "status";
      };
    };
    

  };
}